name: PR Tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Generate docs and check for changes
        run: |
          npm run generate-docs
          if git diff --exit-code docs/SUPPORTED_SITES.md; then
            echo "No changes detected in SUPPORTED_SITES.md"
          else
            echo "SUPPORTED_SITES.md is out of date. Please run 'npm run generate-docs' and commit the changes."
            git diff docs/SUPPORTED_SITES.md
            exit 1
          fi

      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps

      # - name: Run E2E tests
      #   run: npm run e2e

      # - name: Upload test results
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: test-results/
      #     retention-days: 5
